# Generated by Django 5.1.3 on 2026-06-07 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myapp", "0011_alter_product_is_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sync_interval_minutes", models.PositiveIntegerField(default=30)),
                ("full_sync_interval_hours", models.PositiveIntegerField(default=24)),
                ("batch_size", models.PositiveIntegerField(default=100)),
                ("odoo_product_domain", models.JSONField(default=list)),
                ("odoo_fields_to_sync", models.JSONField(default=list)),
                ("auto_create_local_products", models.BooleanField(default=True)),
                (
                    "conflict_resolution",
                    models.CharField(
                        choices=[
                            ("ODOO_WINS", "Odoo wins"),
                            ("LOCAL_WINS", "Local wins"),
                            ("MANUAL", "Manual"),
                        ],
                        default="ODOO_WINS",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full"),
                            ("DELTA", "Delta"),
                            ("MANUAL", "Manual"),
                            ("WEBHOOK", "Webhook"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_fetched", models.PositiveIntegerField(default=0)),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("records_skipped", models.PositiveIntegerField(default=0)),
                ("records_errored", models.PositiveIntegerField(default=0)),
                ("error_detail", models.JSONField(default=dict)),
                ("triggered_by", models.CharField(blank=True, max_length=128)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="OdooProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("odoo_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("odoo_name", models.CharField(max_length=512)),
                ("odoo_sku", models.CharField(blank=True, max_length=128)),
                (
                    "odoo_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("odoo_qty_available", models.FloatField(default=0)),
                ("odoo_active", models.BooleanField(default=True)),
                ("odoo_categ_id", models.PositiveIntegerField(null=True)),
                ("odoo_categ_name", models.CharField(blank=True, max_length=256)),
                ("raw_data", models.JSONField(default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SYNCED", "Synced"),
                            ("CONFLICT", "Conflict"),
                            ("ERROR", "Error"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("sync_error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "local_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="odoo_product",
                        to="myapp.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_synced_at",),
                "indexes": [
                    models.Index(fields=["odoo_id"], name="odoo_product_odoo_id_idx"),
                    models.Index(
                        fields=["sync_status"],
                        name="odoo_product_status_idx",
                    ),
                    models.Index(
                        fields=["last_synced_at"],
                        name="odoo_product_synced_idx",
                    ),
                ],
            },
        ),
    ]
