# Generated by Django 5.1.3 on 2025-03-09 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('decor', 'Home Decor'), ('fashion', 'Fashion & Accessories'), ('garden', 'Garden & Outdoor'), ('art', 'Art & Collectibles'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(blank=True, default='Standard shipping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
