# Generated by Django 5.1.3 on 2025-03-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_product_updated_at_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_upcycled',
            field=models.BooleanField(default=False),
        ),
    ]
